#!/usr/bin/env python
"""Closed-loop load test for the inference API (stdlib only).

    python scripts/load_test.py --url http://127.0.0.1:8080 --date 2025-08-15 \
        --scenario lookup_1 --concurrency 1 8 32 64 --duration 10 --out result.json

Scenarios (what the routing layer actually does):
    lookup_1     GET  /v1/scores, 1 segment        (one edge's risk)
    lookup_100   GET  /v1/scores, 100 segments     (one route's edges)
    score_100    POST /v1/score, 100 segments, operational feed   (model at request time)
    whatif_100   POST /v1/score, 100 segments, caller rainfall scenario
    alerts       GET  /v1/alerts, top 100 of the day

Load is generated by several processes (each running threads), because one Python
process saturates on the GIL long before the server does; the report states the
client configuration so a client-bound result is not mistaken for a server limit.
"""
from __future__ import annotations

import argparse
import json
import multiprocessing as mp
import os
import random
import http.client
import threading
import time
from urllib.parse import urlparse

import numpy as np


class Client:
    """One persistent HTTP/1.1 connection per client thread — what a routing service
    with a connection pool does. (A first version opened a connection per request;
    at >1k req/s that exhausted the macOS ephemeral-port range in TIME_WAIT and
    reported client-side connect failures as server errors.)"""

    def __init__(self, url: str):
        p = urlparse(url)
        self.host, self.port, self.conn = p.hostname, p.port, None
        self.reconnects = 0

    def request(self, method, path, body=None, headers=None):
        for attempt in (0, 1):
            try:
                if self.conn is None:
                    self.conn = http.client.HTTPConnection(self.host, self.port, timeout=30)
                    self.reconnects += 1
                self.conn.request(method, path, body=body, headers=headers or {})
                r = self.conn.getresponse()
                r.read()
                if (r.getheader("Connection") or "").lower() == "close":
                    self.conn.close()
                    self.conn = None
                return r.status, None
            except (http.client.RemoteDisconnected, http.client.CannotSendRequest,
                    ConnectionResetError, BrokenPipeError) as e:
                # server closed an idle keep-alive connection; every endpoint here is
                # idempotent, so one retry on a fresh connection is correct client behaviour
                if self.conn is not None:
                    self.conn.close()
                self.conn = None
                if attempt:
                    return 0, type(e).__name__
            except Exception as e:                 # noqa: BLE001 — a failure is a result
                if self.conn is not None:
                    self.conn.close()
                self.conn = None
                return 0, type(e).__name__
        return 0, "unreachable"


def _request(client: Client, scenario: str, date: str, ids: list[str], rng: random.Random):
    if scenario.startswith("lookup"):
        k = int(scenario.split("_")[1])
        args = ("GET", f"/v1/scores?date={date}&segment_id={','.join(rng.sample(ids, k))}")
    elif scenario == "alerts":
        args = ("GET", f"/v1/alerts?date={date}&tier=alert&limit=100")
    else:
        body = {"date": date, "segment_ids": rng.sample(ids, int(scenario.split("_")[1]))}
        if scenario.startswith("whatif"):
            body["rain_mm"] = [round(rng.uniform(0, 60), 1) for _ in range(61)]
        args = ("POST", "/v1/score", json.dumps(body).encode(), {"Content-Type": "application/json"})
    t = time.perf_counter()
    code, err = client.request(*args)
    return time.perf_counter() - t, code, err


def _proc(url, scenario, date, ids, threads, duration, seed, q):
    lat, codes, errs, stop = [], [], [], time.perf_counter() + duration
    lock = threading.Lock()
    reconnects = [0]

    def loop(i):
        rng = random.Random(seed * 1000 + i)
        client = Client(url)
        while time.perf_counter() < stop:
            dt, c, e = _request(client, scenario, date, ids, rng)
            with lock:
                lat.append(dt)
                codes.append(c)
                if e:
                    errs.append(e)
        with lock:
            reconnects[0] += client.reconnects
    ts = [threading.Thread(target=loop, args=(i,)) for i in range(threads)]
    for t in ts:
        t.start()
    for t in ts:
        t.join()
    q.put((lat, codes, errs, reconnects[0]))


def run_level(url, scenario, date, ids, concurrency, duration) -> dict:
    procs = min(concurrency, max(1, (os.cpu_count() or 2) // 2))
    per = [concurrency // procs + (1 if i < concurrency % procs else 0) for i in range(procs)]
    q = mp.Queue()
    ps = [mp.Process(target=_proc, args=(url, scenario, date, ids, n, duration, i, q))
          for i, n in enumerate(per)]
    t0 = time.perf_counter()
    for p in ps:
        p.start()
    lat, codes, errs, reconnects = [], [], [], 0
    for _ in ps:
        a, b, e, r = q.get()
        lat += a
        codes += b
        errs += e
        reconnects += r
    for p in ps:
        p.join()
    wall = time.perf_counter() - t0
    lat_ms = np.array(lat) * 1000
    ok = sum(1 for c in codes if c == 200)
    return {"scenario": scenario, "concurrency": concurrency, "client_processes": procs,
            "requests": len(codes), "ok": ok, "errors": len(codes) - ok,
            "error_codes": {str(c): codes.count(c) for c in set(codes) if c != 200},
            "client_exceptions": {e: errs.count(e) for e in set(errs)},
            "connections_opened": reconnects,
            "rps": ok / wall, "p50_ms": float(np.percentile(lat_ms, 50)),
            "p95_ms": float(np.percentile(lat_ms, 95)), "p99_ms": float(np.percentile(lat_ms, 99)),
            "max_ms": float(lat_ms.max())}


def main():
    ap = argparse.ArgumentParser()
    ap.add_argument("--url", default="http://127.0.0.1:8080")
    ap.add_argument("--date", required=True)
    ap.add_argument("--scenario", nargs="+", default=["lookup_1"])
    ap.add_argument("--concurrency", nargs="+", type=int, default=[1, 8, 32])
    ap.add_argument("--duration", type=float, default=10)
    ap.add_argument("--ids-from", default=None, help="parquet of scores to draw segment ids from")
    ap.add_argument("--label", default="")
    ap.add_argument("--out", default=None)
    a = ap.parse_args()
    import pandas as pd
    ids = pd.read_parquet(a.ids_from, columns=["segment_id"]).segment_id.tolist()
    rows = []
    for s in a.scenario:
        for c in a.concurrency:
            r = run_level(a.url, s, a.date, ids, c, a.duration)
            r["label"] = a.label
            print(json.dumps(r), flush=True)
            rows.append(r)
    if a.out:
        prev = json.loads(open(a.out).read()) if os.path.exists(a.out) else []
        open(a.out, "w").write(json.dumps(prev + rows, indent=1))


if __name__ == "__main__":
    main()
