import 'package:geolocator/geolocator.dart';

/// One GPS fix captured on the rider's device.
///
/// Serialised 1:1 into the JSON shape expected by the `sync_rider_locations`
/// RPC and into the local offline queue, so a point survives app restarts
/// and re-uploads without duplication (`clientId` is the idempotency key).
class RiderLocationPoint {
  final String clientId;
  final double lat;
  final double lng;
  final DateTime recordedAt;
  final double? accuracyM;
  final double? speedKmph;
  final double? headingDeg;
  final double? altitudeM;
  final int? batteryPercent;
  final String? shipmentId;

  /// True for a point generated by the periodic heartbeat rather than motion.
  final bool heartbeat;

  const RiderLocationPoint({
    required this.clientId,
    required this.lat,
    required this.lng,
    required this.recordedAt,
    this.accuracyM,
    this.speedKmph,
    this.headingDeg,
    this.altitudeM,
    this.batteryPercent,
    this.shipmentId,
    this.heartbeat = false,
  });

  factory RiderLocationPoint.fromPosition(
    Position p, {
    required String clientId,
    String? shipmentId,
    bool heartbeat = false,
  }) {
    final speed = p.speed; // m/s, negative when unknown on some devices
    final heading = p.heading;
    return RiderLocationPoint(
      clientId: clientId,
      lat: p.latitude,
      lng: p.longitude,
      recordedAt: p.timestamp.toUtc(),
      accuracyM: p.accuracy > 0 ? p.accuracy : null,
      speedKmph: speed >= 0 ? speed * 3.6 : null,
      headingDeg: heading >= 0 && heading <= 360 ? heading : null,
      altitudeM: p.altitude,
      shipmentId: shipmentId,
      heartbeat: heartbeat,
    );
  }

  /// JSON accepted by `public.sync_rider_locations(jsonb)`.
  Map<String, dynamic> toRpcJson() => {
        'client_id': clientId,
        'lat': lat,
        'lng': lng,
        'recorded_at': recordedAt.toUtc().toIso8601String(),
        if (accuracyM != null) 'accuracy_m': accuracyM,
        if (speedKmph != null) 'speed_kmph': speedKmph,
        if (headingDeg != null) 'heading_deg': headingDeg,
        if (altitudeM != null) 'altitude_m': altitudeM,
        if (batteryPercent != null) 'battery_percent': batteryPercent,
        if (shipmentId != null) 'shipment_id': shipmentId,
        'source': heartbeat ? 'mobile-heartbeat' : 'mobile',
      };

  /// Local queue representation (superset of the RPC shape).
  Map<String, dynamic> toJson() => {...toRpcJson(), 'heartbeat': heartbeat};

  factory RiderLocationPoint.fromJson(Map<String, dynamic> j) => RiderLocationPoint(
        clientId: j['client_id'] as String,
        lat: (j['lat'] as num).toDouble(),
        lng: (j['lng'] as num).toDouble(),
        recordedAt: DateTime.parse(j['recorded_at'] as String).toUtc(),
        accuracyM: (j['accuracy_m'] as num?)?.toDouble(),
        speedKmph: (j['speed_kmph'] as num?)?.toDouble(),
        headingDeg: (j['heading_deg'] as num?)?.toDouble(),
        altitudeM: (j['altitude_m'] as num?)?.toDouble(),
        batteryPercent: (j['battery_percent'] as num?)?.toInt(),
        shipmentId: j['shipment_id'] as String?,
        heartbeat: j['heartbeat'] == true,
      );

  RiderLocationPoint copyWith({String? shipmentId, bool? heartbeat, String? clientId, DateTime? recordedAt}) =>
      RiderLocationPoint(
        clientId: clientId ?? this.clientId,
        lat: lat,
        lng: lng,
        recordedAt: recordedAt ?? this.recordedAt,
        accuracyM: accuracyM,
        speedKmph: speedKmph,
        headingDeg: headingDeg,
        altitudeM: altitudeM,
        batteryPercent: batteryPercent,
        shipmentId: shipmentId ?? this.shipmentId,
        heartbeat: heartbeat ?? this.heartbeat,
      );

  @override
  String toString() =>
      'RiderLocationPoint(${lat.toStringAsFixed(5)}, ${lng.toStringAsFixed(5)} @ $recordedAt'
      '${accuracyM == null ? '' : ' ±${accuracyM!.round()}m'})';
}
