// Bakes OSRM road geometry into the app and seeds PostGIS for GeoServer.
//
//   dart run tool/generate_geodata.dart [OSRM_URL]
//
// Writes:
//   lib/shared/map/generated/geo_snapshot.g.dart  — highway lines + trip
//       routes/detour used offline and before live routing responds
//   backend/geoserver/sql/02_seed.sql             — the same geometry and the
//       app's demo incidents / zones / fleet for the GeoServer layers
//
// Re-run after changing NerGeo waypoints, zones or the trip scenarios.
// Default OSRM is the public demo server (~1 req/s, ~30 requests total).

import 'dart:convert';
import 'dart:io';

import 'package:ner_logistics/mock_data/mock_fleet.dart';
import 'package:ner_logistics/mock_data/mock_incidents.dart'
    hide mockDistricts, mockFleet;
import 'package:ner_logistics/mock_data/mock_route_scenarios.dart';
import 'package:ner_logistics/services/geo/geo_math.dart';
import 'package:ner_logistics/services/routing/osrm_client.dart';
import 'package:ner_logistics/services/routing/trip_plan.dart';
import 'package:ner_logistics/shared/map/map_models.dart';
import 'package:ner_logistics/shared/map/ner_geo.dart';

const _highwayToleranceM = 25.0;
const _tripToleranceM = 8.0;

Future<void> main(List<String> args) async {
  final osrmUrl = args.isNotEmpty ? args.first : 'https://router.project-osrm.org';
  final osrm = OsrmClient(baseUrl: osrmUrl);
  final planner = TripPlanner(osrm);
  stdout.writeln('OSRM: $osrmUrl');

  final highways = <String, String>{};
  for (final e in NerGeo.highwayWaypoints.entries) {
    final r = (await osrm.route(e.value, steps: false)).first;
    final line = GeoMath.simplify(r.geometry, _highwayToleranceM);
    highways[e.key] = GeoMath.encodePolyline(line);
    stdout.writeln('  ${e.key.padRight(7)} ${(r.distanceM / 1000).toStringAsFixed(1)} km'
        '  ${r.geometry.length} → ${line.length} pts');
  }

  final field = await planner.plan(fieldTripScenario);
  final hazardOffset = GeoMath.distanceToLineM(
      fieldTripScenario.hazardPoint!, field.route.geometry);
  stdout.writeln('  field trip ${(field.lengthM / 1000).toStringAsFixed(1)} km, '
      'hazard ${field.hazard!.kmLabel} (${hazardOffset.round()} m off route), '
      'vehicle at Km ${(field.vehicleM / 1000).round()}');
  if (hazardOffset > 500) {
    stderr.writeln('  WARNING: hazard point is not on the routed road');
  }
  final detour = await planner.detour(field);
  stdout.writeln(detour.result.found
      ? '  detour +${detour.result.extraKm.toStringAsFixed(1)} km, '
          '+${detour.result.extraTime.inMinutes} min via ${detour.result.via ?? '?'}'
      : '  WARNING: no detour found around the field trip hazard');

  final rider = await planner.plan(riderTripScenario);
  stdout.writeln('  rider trip ${(rider.lengthM / 1000).toStringAsFixed(1)} km');
  osrm.close();

  final snapshot = StringBuffer()
    ..writeln('// GENERATED by tool/generate_geodata.dart — do not edit by hand.')
    ..writeln('// ignore_for_file: lines_longer_than_80_chars')
    ..writeln()
    ..writeln("const kSnapshotGeneratedAt = '${DateTime.now().toUtc().toIso8601String()}';")
    ..writeln("const kSnapshotOsrmUrl = '$osrmUrl';")
    ..writeln()
    ..writeln('const Map<String, String> kHighwayPolylines = {');
  for (final e in highways.entries) {
    snapshot.writeln("  '${e.key}': r'${e.value}',");
  }
  snapshot
    ..writeln('};')
    ..writeln()
    ..writeln("const String kFieldTripRouteJson = r'''${jsonEncode(field.route.toJson(simplifyToleranceM: _tripToleranceM))}''';")
    ..writeln()
    ..writeln("const String kFieldTripDetourJson = r'''${jsonEncode(detourToJson(detour.result, simplifyM: _tripToleranceM))}''';")
    ..writeln()
    ..writeln("const String kRiderTripRouteJson = r'''${jsonEncode(rider.route.toJson(simplifyToleranceM: _tripToleranceM))}''';");
  File('lib/shared/map/generated/geo_snapshot.g.dart')
      .writeAsStringSync(snapshot.toString());

  File('backend/geoserver/sql/02_seed.sql').writeAsStringSync(_seedSql(highways));
  stdout.writeln('Wrote geo_snapshot.g.dart and 02_seed.sql');
}

String _q(String s) => "'${s.replaceAll("'", "''")}'";
String _pt(double lat, double lng) => 'ST_SetSRID(ST_MakePoint($lng, $lat), 4326)';

String _seedSql(Map<String, String> highways) {
  final b = StringBuffer()
    ..writeln('-- GENERATED by tool/generate_geodata.dart — do not edit by hand.')
    ..writeln('-- Demo data mirroring the app (lib/shared/map/ner_geo.dart, lib/mock_data).')
    ..writeln()
    ..writeln('TRUNCATE ner.highways, ner.incidents, ner.risk_zones, ner.safe_zones, ner.depots, ner.vehicles RESTART IDENTITY;')
    ..writeln();

  for (final e in highways.entries) {
    b.writeln('INSERT INTO ner.highways (highway_id, geom) VALUES '
        '(${_q(e.key)}, ST_SetSRID(ST_LineFromEncodedPolyline(${_q(e.value)}, 6), 4326));');
  }
  b.writeln();

  for (final i in mockIncidents) {
    final p = NerGeo.locate(i.location, i.route);
    final town = NerGeo.nearestTown(p);
    b.writeln('INSERT INTO ner.incidents (id, type, type_label, severity, status, route, location, area, state, reported, geom) VALUES '
        '(${_q(i.id)}, ${_q(i.type.name)}, ${_q(i.typeLabel)}, ${_q(i.severity.name)}, ${_q(i.statusLabel)}, '
        '${_q(i.route)}, ${_q(i.location)}, ${_q(town.name)}, ${_q(town.state)}, ${_q(i.time)}, ${_pt(p.latitude, p.longitude)});');
  }
  b.writeln();

  // Circles become 32-sided polygons; local analytics use the same circles.
  for (final z in [...NerGeo.floodZones, ...NerGeo.landslideZones]) {
    b.writeln('INSERT INTO ner.risk_zones (kind, name, susceptibility, source, geom) VALUES '
        '(${_q(z.kind.name)}, ${_q(z.label)}, ${_q(z.kind == MapZoneKind.landslide ? 'high' : 'moderate')}, '
        "'demo', ST_Buffer(${_pt(z.center.latitude, z.center.longitude)}::geography, ${z.radiusMeters}, 'quad_segs=8')::geometry);");
  }
  b.writeln();

  for (final z in NerGeo.safeZones) {
    b.writeln('INSERT INTO ner.safe_zones (name, radius_m, geom) VALUES '
        '(${_q(z.label)}, ${z.radiusMeters}, ${_pt(z.center.latitude, z.center.longitude)});');
  }
  for (final p in NerGeo.infrastructure) {
    b.writeln('INSERT INTO ner.depots (name, kind, geom) VALUES '
        '(${_q(p.label)}, ${_q(p.kind.name)}, ${_pt(p.point.latitude, p.point.longitude)});');
  }
  b.writeln();

  final byId = {for (final v in mockFleet) v.id: v};
  for (final v in NerGeo.vehicles(mockFleet)) {
    final f = byId[v.id]!;
    b.writeln('INSERT INTO ner.vehicles (vehicle_id, route, destination, status, risk, geom) VALUES '
        '(${_q(v.id)}, ${_q(NerGeo.routeIdOf(f.route))}, ${_q(f.destination)}, ${_q(f.statusLabel)}, '
        '${_q(f.risk.name)}, ${_pt(v.point.latitude, v.point.longitude)});');
  }
  return b.toString();
}
