import '../core/demo/demo_mode.dart';
import 'models.dart';

const List<Incident> _demoIncidents = [
  Incident(
    id: 'INC-2026-041',
    type: IncidentType.flood,
    typeLabel: 'Flash Flood',
    location: 'Barpeta',
    route: 'NH-27',
    severity: Priority.critical,
    reporter: 'Citizen SMS',
    time: '8 min ago',
    verified: false,
    assignedOfficer: '—',
    statusLabel: 'Pending',
  ),
  Incident(
    id: 'INC-2026-042',
    type: IncidentType.roadBlockage,
    typeLabel: 'Convoy At Risk',
    location: 'NH-2 Zone',
    route: 'NH-2',
    severity: Priority.high,
    reporter: 'Fleet system',
    time: '18 min ago',
    verified: false,
    assignedOfficer: '—',
    statusLabel: 'Pending',
  ),
  Incident(
    id: 'INC-2026-043',
    type: IncidentType.infraDamage,
    typeLabel: 'Bridge Damage',
    location: 'Tawang',
    route: 'NH-13',
    severity: Priority.critical,
    reporter: 'FO D. Wangmo',
    time: '40 min ago',
    verified: true,
    assignedOfficer: 'Response Team B',
    statusLabel: 'Escalated',
  ),
  Incident(
    id: 'INC-2026-044',
    type: IncidentType.landslide,
    typeLabel: 'Landslide',
    location: 'NH-306 Km 54',
    route: 'NH-306',
    severity: Priority.high,
    reporter: 'FO K. Rabha',
    time: '1 hr ago',
    verified: true,
    assignedOfficer: 'K. Rabha',
    statusLabel: 'Active',
  ),
  Incident(
    id: 'INC-2026-045',
    type: IncidentType.roadBlockage,
    typeLabel: 'Road Blockage',
    location: 'NH-6 Km 120',
    route: 'NH-6',
    severity: Priority.medium,
    reporter: 'Fleet system',
    time: '1 hr 20 min ago',
    verified: true,
    assignedOfficer: 'A. Das',
    statusLabel: 'Active',
  ),
  Incident(
    id: 'INC-2026-038',
    type: IncidentType.flood,
    typeLabel: 'Waterlogging',
    location: 'Guwahati GS Road',
    route: 'NH-27',
    severity: Priority.medium,
    reporter: 'Citizen app',
    time: 'Yesterday',
    verified: true,
    assignedOfficer: 'A. Das',
    statusLabel: 'Resolved',
  ),
  Incident(
    id: 'INC-2026-039',
    type: IncidentType.other,
    typeLabel: 'Fallen Tree',
    location: 'Jorhat bypass',
    route: 'NH-37',
    severity: Priority.low,
    reporter: 'Citizen app',
    time: 'Yesterday',
    verified: true,
    assignedOfficer: 'K. Rabha',
    statusLabel: 'Resolved',
  ),
];

/// The sample data while demo mode is on, otherwise empty.
List<Incident> get mockIncidents => DemoMode.enabled ? _demoIncidents : const [];

const List<DistrictSummary> _demoDistricts = [
  DistrictSummary(
    name: 'Dimapur',
    state: 'Nagaland',
    risk: Priority.critical,
    accessScore: 81,
    incidentCount: 6,
    criticalCount: 3,
    blockedRoutes: 4,
    logisticsNote: '6 delayed',
    statusLabel: 'On alert',
  ),
  DistrictSummary(
    name: 'Kohima',
    state: 'Nagaland',
    risk: Priority.critical,
    accessScore: 74,
    incidentCount: 3,
    criticalCount: 2,
    blockedRoutes: 2,
    logisticsNote: '2 held',
    statusLabel: 'On alert',
  ),
  DistrictSummary(
    name: 'Kamrup',
    state: 'Assam',
    risk: Priority.high,
    accessScore: 58,
    incidentCount: 4,
    criticalCount: 0,
    blockedRoutes: 1,
    logisticsNote: '1 delayed',
    statusLabel: 'Monitoring',
  ),
  DistrictSummary(
    name: 'Papum Pare',
    state: 'Arunachal Pr.',
    risk: Priority.medium,
    accessScore: 39,
    incidentCount: 1,
    criticalCount: 0,
    blockedRoutes: 0,
    logisticsNote: 'On time',
    statusLabel: 'Stable',
  ),
  DistrictSummary(
    name: 'Imphal West',
    state: 'Manipur',
    risk: Priority.low,
    accessScore: 21,
    incidentCount: 0,
    criticalCount: 0,
    blockedRoutes: 0,
    logisticsNote: 'On time',
    statusLabel: 'Stable',
  ),
  DistrictSummary(
    name: 'Aizawl',
    state: 'Mizoram',
    risk: Priority.medium,
    accessScore: 44,
    incidentCount: 1,
    criticalCount: 0,
    blockedRoutes: 1,
    logisticsNote: '1 delayed',
    statusLabel: 'Monitoring',
  ),
];

/// The sample data while demo mode is on, otherwise empty.
List<DistrictSummary> get mockDistricts => DemoMode.enabled ? _demoDistricts : const [];

const List<FleetVehicle> _demoFleet = [
  FleetVehicle(
    id: 'TRK-1042',
    route: 'NH-29',
    destination: 'Kohima',
    statusLabel: 'Delayed',
    risk: Priority.high,
    eta: '+2h',
  ),
  FleetVehicle(
    id: 'TRK-1088',
    route: 'NH-2',
    destination: 'Kohima',
    statusLabel: 'At risk',
    risk: Priority.critical,
    eta: '—',
  ),
  FleetVehicle(
    id: 'TRK-1015',
    route: 'NH-29',
    destination: 'Dimapur',
    statusLabel: 'Moving',
    risk: Priority.low,
    eta: '16:05',
  ),
  FleetVehicle(
    id: 'TRK-0994',
    route: 'NH-39',
    destination: 'Chumukedima',
    statusLabel: 'Moving',
    risk: Priority.low,
    eta: '11:20',
  ),
];

/// The sample data while demo mode is on, otherwise empty.
List<FleetVehicle> get mockFleet => DemoMode.enabled ? _demoFleet : const [];
