import 'models.dart';

const mockRiderDeliveries = [
  DeliveryAssignment(
    id: 'ASN-4821',
    tripId: 'TRP-R-4821',
    riderId: 'NER-RD-1184',
    vehicleId: 'TRK-NE-2047',
    cargo: 'Essential medicines · 2.4 tonnes',
    priority: Priority.critical,
    origin: 'Guwahati Medical Depot',
    destination: 'Nongpoh Civil Hospital',
    recipient: 'Dr. M. Khongwir',
    window: 'Today · 13:00–15:00',
    risk: RiskLevel.caution,
    eta: '14:12',
    distanceRemaining: '42 km',
    progress: 58,
    status: RiderTripStatus.enRoute,
    decision: AssignmentDecision.accepted,
  ),
  DeliveryAssignment(
    id: 'ASN-4828',
    tripId: 'TRP-R-4828',
    riderId: 'NER-RD-1184',
    vehicleId: 'TRK-NE-2047',
    cargo: 'Relief materials · 1.1 tonnes',
    priority: Priority.high,
    origin: 'Nongpoh Warehouse',
    destination: 'Umsning Relief Camp',
    recipient: 'District Relief Cell',
    window: 'Today · 16:30–18:00',
    risk: RiskLevel.clear,
    eta: '17:05',
    distanceRemaining: '18 km',
    progress: 0,
    status: RiderTripStatus.assigned,
    decision: AssignmentDecision.pending,
  ),
];